// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_pmbOxXFFGnNG2aV6IIwtLO2vj3agXL0',
    appId: '1:645188221144:web:d10870f6a022d885647fad',
    messagingSenderId: '645188221144',
    projectId: 'explorer-kids',
    authDomain: 'explorer-kids.firebaseapp.com',
    storageBucket: 'explorer-kids.appspot.com',
    measurementId: 'G-92SGEYTNE3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAId1wwKcWTYFXNrtRDzkBmAZC-ALozEpU',
    appId: '1:645188221144:android:3503f08f240e1605647fad',
    messagingSenderId: '645188221144',
    projectId: 'explorer-kids',
    storageBucket: 'explorer-kids.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAPpbGQbSv1Lwej982ebQ0gtR2zXvc-as',
    appId: '1:645188221144:ios:b65cd1ecdb393195647fad',
    messagingSenderId: '645188221144',
    projectId: 'explorer-kids',
    storageBucket: 'explorer-kids.appspot.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAPpbGQbSv1Lwej982ebQ0gtR2zXvc-as',
    appId: '1:645188221144:ios:576245be04bedd39647fad',
    messagingSenderId: '645188221144',
    projectId: 'explorer-kids',
    storageBucket: 'explorer-kids.appspot.com',
    iosBundleId: 'com.example.firebase.RunnerTests',
  );
}
